# Generated by Django 4.2.5 on 2023-10-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField(max_length=100)),
                ('l_name', models.TextField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=30)),
                ('package_selected', models.CharField(choices=[('1 MONTH', '1 MONTH'), ('3 MONTHS', '3 MONTHS'), ('6 MONTHS', '6 MONTHS'), ('12 MONTHS', '12 MONTHS')], max_length=30)),
                ('payment', models.CharField(choices=[('PAID', 'PAID'), ('DUE', 'DUE')], max_length=30)),
                ('health_conditions', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
