# Generated by Django 4.2.5 on 2023-11-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_member_age_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mobile_number',
            field=models.IntegerField(default='+977'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=''),
        ),
    ]
