# Generated by Django 4.2.6 on 2023-11-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0005_member_address'),
        ('User', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('initial_biceps_size', models.IntegerField()),
                ('initial_chest_size', models.IntegerField()),
                ('initial_heart_rate', models.IntegerField()),
                ('initial_thigh_size', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.member')),
            ],
        ),
    ]
