# Generated by Django 4.2.6 on 2023-11-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_profile_phone_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
