# Generated by Django 4.2.6 on 2023-11-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='MALE', max_length=100),
        ),
    ]
